language: cpp

compiler:
  - gcc
    # maybe try later, now segfaults
    #  - clang

# sudo: false

before_install:
  # install GCC-4.8
  # - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  # - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  # - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # install Boost
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost1.54-dev_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost1.54-dev_1.54.0-4ubuntu3_amd64.deb" ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-system1.54.0_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-system1.54.0_1.54.0-4ubuntu3_amd64.deb" ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-system1.54-dev_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-system1.54-dev_1.54.0-4ubuntu3_amd64.deb" ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-filesystem1.54.0_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-filesystem1.54.0_1.54.0-4ubuntu3_amd64.deb" ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-filesystem1.54-dev_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-filesystem1.54-dev_1.54.0-4ubuntu3_amd64.deb" ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-test1.54.0_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-test1.54.0_1.54.0-4ubuntu3_amd64.deb" ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget "http://cz.archive.ubuntu.com/ubuntu/pool/main/b/boost1.54/libboost-test1.54-dev_1.54.0-4ubuntu3_amd64.deb" && sudo dpkg --install "libboost-test1.54-dev_1.54.0-4ubuntu3_amd64.deb" ; fi

script:
  - make debug
  - make test
  - make release
  - make test

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libstdc++-4.8-dev

cache: ccache

os:
  - linux
  - osx

dist: trusty
